# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
  - release
  - devel

r_packages:
  - scales
  - tidyverse

addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libgeos-dev
      - libproj-dev

after_success:
  - R CMD INSTALL .
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
